---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000 # Optional: Specify the nodePort, or Kubernetes will assign one automatically
  type: NodePort # Change the type to NodePort
  selector:
    role: frontend
